### ISSUE TITLE
Stopping the server

### ISSUE THREAD

**Issue by katywings** [oakserver/oak#77]
First and foremost: keep up the good work, i like where this project is going (: 

I tried to implement an fs.watch logic that restarts oak on file change. For this I added the AbortController as mentioned in the README and I added `controller.abort()` to my fs.watch. Unfortunately neither the promise from app.listen was ever resolved, nor was the underlying server closed - it also seems like `server.close()` is not called in https://github.com/oakserver/oak/blob/master/application.ts#L226

Do I misunderstand the idea behind the AbortController? Or is this just not fully implemented?

**Comment by kitsonk** [comment]
Bah! I thought I had, but clearly my tests mocks were insufficient.  Back to the drawing board.  If you had a simple example of the `fs.watch`, it would be super useful and I can add something like it to the examples (and make sure my mocks behave properly too).  If not, no worries.

**Comment by katywings** [comment]
@kitsonk I created in the meantime a little fork of Oak, added as a workaround a ref parameter to `app.listen` and extended it so that it sets `ref.current = server` ':). Il send you links to the workaround and to the fs watch thingy later, its unfortunately not committed yet xD.

**Comment by kitsonk** [comment]
No worries... I suspect I will try to fix it in the next few hours.  I suspect it is because I assumed ignorantly that if I returned out of the async loop, that it would close the server... 🤦 Upon reflection that isn't very likely.

**Comment by katywings** [comment]
Little update from my side: so as I promised it a few days ago, I committed my workaround :D

Changes:
  - https://github.com/lufrai/oak/commit/20905121bc2771b1e4b3272e4d028b57c6d46352

Usage: 
  - https://github.com/nexojs/nexo/blob/master/mod.ts#L160
  - https://github.com/nexojs/nexo/blob/master/mod.ts#L127

Let me know if you have any questions or if I can help you to figure out a non-workaround strategy for oak ;)

**Comment by kitsonk** [comment]
Ah, sorry, forgot to come back to this issue. I believe I fixed it in master and added tests. 🤦

**Comment by alxtsg** [comment]
Looks like I am having a similar problem. I implemented a very simply API to experiment with Deno. I have the following test case:

```
Deno.test('health check API', async (): Promise<void> => {
  const abortController = new AbortController();
  const { signal } = abortController;
  const instance = app.listen({
    hostname,
    port: config.port,
    signal
  });
  const response = await fetch(`${endpoint}/api/health`);
  assertStrictEq(response.status, 200);
  abortController.abort();
  await instance;
});
```

The intention is to start the server, send a request to the API, make sure the response status code is `200`, and close the server. However, when I run the test, `await instance` never finish and the test never complete.

**Comment by kitsonk** [comment]
@alxtsg that code doesn't make sense.  There is no middleware for the application, therefore nothing to process requests with.  I suspect there is something going on internally, but the fix would be to reject the listen in this case.

**Comment by alxtsg** [comment]
> @alxtsg that code doesn't make sense. There is no middleware for the application, therefore nothing to process requests with. I suspect there is something going on internally, but the fix would be to reject the listen in this case.

Oh the middlewares are loaded in another module.

```
// app.ts
const app = new Application();

app.use(accessLogger);

app.use(healthRouter.routes());

export default app;
```

And the `Application` is imported into the test:

```
// app_test.ts
import app from './app.ts';

// (The test cases.)
```

**Comment by katywings** [comment]
@kitsonk I tried it out with your master branch :). I still can't close the server on my command on that branch.

The current workflow looks something like this:
Start:
- promise = app.listen

Restart:
- abortController.abort()
- await promise;
- oak resolves promise only after the next http request (but i need it to really stop now, not later at some point ;))
- promise = app.listen
  - And i still get a "Address already in use" here :/
  - Don't understand exactly why i am still getting this, since you have the server.close in `https://github.com/oakserver/oak/blob/master/application.ts#L195`

my code:
```js
let abortController;
let listener;

const start = function() {
  if (abortController && listener) {
    abortController.abort();
    await listener;
  }

  abortController = new AbortController();
  const app = new Application();

  // ...middlewares

  listener = app.listen({
    port,
    signal: abortController.signal,
  });
}
```

**Comment by kitsonk** [comment]
Yes, sorry folks.  I think I fixed it in 4bc2c76cad7e3ffed3725e29dedbbd0d5b7e3925.  It was a situation where it needed to process another request to actually close the server.  I had run into an issue where if you were processing middleware (like you abort in middleware) it caused all sorts of carnage, so I didn't do that, but then it did mean that it wouldn't see that close until too late.  Now it tracks if it handling requests, and if it isn't it will close, which should resolve the promise, otherwise it will finish any in flight requests before closing.  I need a better test "mock" as my current one is limited, and giving me a false sense of fixing the problem.

**Comment by katywings** [comment]
@kitsonk I ran my same code again, and now with your 4bc2c76 it just works. Insane work, thank you a lot :woman_dancing: !

**Comment by kitsonk** [comment]
Cool!

**Comment by acrodrig** [comment]
Quick question on this topic: why not just have an `app.close` method? It could encapsulate the abort controller and make it easy/easier to use.
